/*
	TTC Shop variables.
*/


TTC_SHOP_LOCATION_BASE = 0;
TTC_SHOP_LOCATION_SECTOR = 1;
TTC_SHOP_LOCATION_MOBILE = 2;
TTC_SHOP_LOCATION_HARBOR = 3;
TTC_SHOP_LOCATION_AIRPORT = 4;

TTC_SHOP_location = TTC_SHOP_LOCATION_BASE;
