#define TTC_SHOP_MARGIN_H						0.002 * safezoneW
#define TTC_SHOP_MARGIN_V						0.002 * safezoneH

// Categories

#define TTC_SHOP_DIALOG_CATEGORIES_LIST_W			0.15 * safezoneW
#define TTC_SHOP_DIALOG_CATEGORIES_LIST_H			0.60 * safezoneH
#define TTC_SHOP_DIALOG_CATEGORIES_LIST_X			(safezoneX + (safezoneW / 2)) - (0.368 * safezoneW)
#define TTC_SHOP_DIALOG_CATEGORIES_LIST_Y			safezoneY + (0.20 * safezoneH)

// Articles

#define TTC_SHOP_DIALOG_ARTICLES_LIST_W				0.25 * safezoneW
#define TTC_SHOP_DIALOG_ARTICLES_LIST_H				0.60 * safezoneH
#define TTC_SHOP_DIALOG_ARTICLES_LIST_X				TTC_SHOP_DIALOG_CATEGORIES_LIST_X + TTC_SHOP_DIALOG_CATEGORIES_LIST_W + TTC_SHOP_MARGIN_H
#define TTC_SHOP_DIALOG_ARTICLES_LIST_Y				safezoneY + (0.20 * safezoneH)

#define TTC_SHOP_DIALOG_ARTICLES_TITLE_W			TTC_SHOP_DIALOG_ARTICLES_LIST_W
#define TTC_SHOP_DIALOG_ARTICLES_TITLE_H			0.034 * safezoneH
#define TTC_SHOP_DIALOG_ARTICLES_TITLE_X			TTC_SHOP_DIALOG_ARTICLES_LIST_X
#define TTC_SHOP_DIALOG_ARTICLES_TITLE_Y			TTC_SHOP_DIALOG_ARTICLES_LIST_Y - TTC_SHOP_DIALOG_ARTICLES_TITLE_H

// Shopping card

#define TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_W		0.25 * safezoneW
#define TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_H		0.55 * safezoneH
#define TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_X		TTC_SHOP_DIALOG_ARTICLES_LIST_X + TTC_SHOP_DIALOG_ARTICLES_LIST_W + TTC_SHOP_MARGIN_H
#define TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_Y		safezoneY + (0.20 * safezoneH)

#define TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_W		TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_W
#define TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_H		0.034 * safezoneH
#define TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_X		TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_X
#define TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_Y		TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_Y - TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_H

#define TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_W		TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_W
#define TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_H		(0.05 * safezoneH) - TTC_SHOP_MARGIN_V
#define TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_X		TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_X
#define TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_Y		TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_Y + TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_H + TTC_SHOP_MARGIN_V

// Buttons

#define TTC_SHOP_DIALOG_BUY_BUTTON_W				0.08 * safezoneW
#define TTC_SHOP_DIALOG_BUY_BUTTON_H				0.08 * safezoneH
#define TTC_SHOP_DIALOG_BUY_BUTTON_X				TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_X + TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_W + TTC_SHOP_MARGIN_H
#define TTC_SHOP_DIALOG_BUY_BUTTON_Y				safezoneY + (0.20 * safezoneH)

#define TTC_SHOP_DIALOG_CANCEL_BUTTON_W				TTC_SHOP_DIALOG_BUY_BUTTON_W
#define TTC_SHOP_DIALOG_CANCEL_BUTTON_H				0.03 * safezoneH
#define TTC_SHOP_DIALOG_CANCEL_BUTTON_X				TTC_SHOP_DIALOG_BUY_BUTTON_X
#define TTC_SHOP_DIALOG_CANCEL_BUTTON_Y				TTC_SHOP_DIALOG_BUY_BUTTON_Y + TTC_SHOP_DIALOG_BUY_BUTTON_H + TTC_SHOP_MARGIN_V


class TTC_SHOP_ShopDialog {

	idd = 5000;
	movingenabled = 0;
	
	class Controls {
		
		class TTC_SHOP_Categories_List: TTC_UI_Listbox {
			idc = 5101;

			x = TTC_SHOP_DIALOG_CATEGORIES_LIST_X;
			y = TTC_SHOP_DIALOG_CATEGORIES_LIST_Y;
			w = TTC_SHOP_DIALOG_CATEGORIES_LIST_W;
			h = TTC_SHOP_DIALOG_CATEGORIES_LIST_H;
			
			sizeEx = "0.025 / (getResolution select 5)";
		};
		
		class TTC_SHOP_Articles_Title : TTC_UI_Text {
		
			idc					= 5200;
			text				= "Articles";
			sizeEx 				= "0.025 / (getResolution select 5)";
			style 				= ST_CENTER;
			colorBackground[]	= COLOR_BLACK_A75;

			x = TTC_SHOP_DIALOG_ARTICLES_TITLE_X;
			y = TTC_SHOP_DIALOG_ARTICLES_TITLE_Y;
			w = TTC_SHOP_DIALOG_ARTICLES_TITLE_W;
			h = TTC_SHOP_DIALOG_ARTICLES_TITLE_H;
		};
		
		class TTC_SHOP_Articles_List: TTC_UI_Listbox {
			idc = 5201;
			
			x = TTC_SHOP_DIALOG_ARTICLES_LIST_X;
			y = TTC_SHOP_DIALOG_ARTICLES_LIST_Y;
			w = TTC_SHOP_DIALOG_ARTICLES_LIST_W;
			h = TTC_SHOP_DIALOG_ARTICLES_LIST_H;
		};
		
		class TTC_SHOP_ShoppingCard_Title : TTC_UI_Text {
		
			idc					= 5300;
			text				= "Shopping Card";
			sizeEx 				= "0.025 / (getResolution select 5)";
			style 				= ST_CENTER;
			colorBackground[]	= COLOR_BLACK_A75;

			x = TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_X;
			y = TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_Y;
			w = TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_W;
			h = TTC_SHOP_DIALOG_SHOPPING_CARD_TITLE_H;
		};
		
		class TTC_SHOP_ShoppingCard_List: TTC_UI_Listbox {
		
			idc = 5301;
			
			x = TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_X;
			y = TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_Y;
			w = TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_W;
			h = TTC_SHOP_DIALOG_SHOPPING_CARD_LIST_H;
		};
		
		class TTC_SHOP_ShoppingCard_Costs : TTC_UI_Text {
		
			idc					= 5302;
			text				= "3500 BTC";
			sizeEx 				= "0.025 / (getResolution select 5)";
			style 				= ST_RIGHT;
			colorBackground[]	= COLOR_BLACK_A100;

			x = TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_X;
			y = TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_Y;
			w = TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_W;
			h = TTC_SHOP_DIALOG_SHOPPING_CARD_COSTS_H;
		};
		
		class TTC_SHOP_Buy_Button: TTC_UI_ButtonSuccess {
		
			idc		= 5401;
			text	= "Buy"; //--- ToDo: Localize;
			sizeEx	= "0.038 / (getResolution select 5)";
			
			x = TTC_SHOP_DIALOG_BUY_BUTTON_X;
			y = TTC_SHOP_DIALOG_BUY_BUTTON_Y;
			w = TTC_SHOP_DIALOG_BUY_BUTTON_W;
			h = TTC_SHOP_DIALOG_BUY_BUTTON_H;
		};
		
		class TTC_SHOP_Cancel_Button: TTC_UI_Button {
		
			idc = 5402;
			text = "Cancel"; //--- ToDo: Localize;
			
			x = TTC_SHOP_DIALOG_CANCEL_BUTTON_X;
			y = TTC_SHOP_DIALOG_CANCEL_BUTTON_Y;
			w = TTC_SHOP_DIALOG_CANCEL_BUTTON_W;
			h = TTC_SHOP_DIALOG_CANCEL_BUTTON_H;
			
			action = "closeDialog 0";
		};
	};
};


