/*
    Created by BauerMitFackel
*/

// WIDTH and HEIGHT
#define TTC_SHOP_UI_CATEGORY_LIST_HEADER_W			TTC_SHOP_UI_COLUMN_LEFT_W
#define TTC_SHOP_UI_CATEGORY_LIST_HEADER_H			TTC_SHOP_UI_COLUMN_HEADER_H
#define TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_W		TTC_SHOP_UI_COLUMN_LEFT_W
#define TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_H		TTC_SHOP_UI_COLUMN_LEFT_H - TTC_SHOP_UI_CATEGORY_LIST_HEADER_H
#define TTC_SHOP_UI_CATEGORY_LIST_W					TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_W
#define TTC_SHOP_UI_CATEGORY_LIST_H					TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_H
// X and Y
#define TTC_SHOP_UI_CATEGORY_LIST_HEADER_X			TTC_SHOP_UI_COLUMN_LEFT_X
#define TTC_SHOP_UI_CATEGORY_LIST_HEADER_Y			TTC_SHOP_UI_COLUMN_LEFT_Y
#define TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_X		TTC_SHOP_UI_COLUMN_LEFT_X
#define TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_Y		TTC_SHOP_UI_CATEGORY_LIST_HEADER_Y + TTC_SHOP_UI_CATEGORY_LIST_HEADER_H
#define TTC_SHOP_UI_CATEGORY_LIST_X					TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_X
#define TTC_SHOP_UI_CATEGORY_LIST_Y					TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_Y


class TTC_SHOP_ShopDialog_CategoryList_Header: TTC_UI_Text {
			
	idc					= 51001;
	moving				= true;
	style				= TTC_UI_STYLE_CENTER;
	colorBackground[]	= TTC_UI_COLOR_BLACK_A25;
	text				= "CATEGORIES";
	x 					= TTC_SHOP_UI_CATEGORY_LIST_HEADER_X;
	y 					= TTC_SHOP_UI_CATEGORY_LIST_HEADER_Y;
	w 					= TTC_SHOP_UI_CATEGORY_LIST_HEADER_W;
	h 					= TTC_SHOP_UI_CATEGORY_LIST_HEADER_H;
};
		
class TTC_SHOP_ShopDialog_CategoryList_Background: TTC_UI_Background {
	
	idc					= 51002;
	x					= TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_X;
	y					= TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_Y;
	w					= TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_W;
	h					= TTC_SHOP_UI_CATEGORY_LIST_BACKGROUND_H;
};

class TTC_SHOP_ShopDialog_CategoryList: TTC_UI_ListNBox {

	idc					= 51003;
	rowHeight			= 0.07;
	columns[]			= {-0.001};
	x 					= TTC_SHOP_UI_CATEGORY_LIST_X;
	y 					= TTC_SHOP_UI_CATEGORY_LIST_Y;
	w 					= TTC_SHOP_UI_CATEGORY_LIST_W;
	h 					= TTC_SHOP_UI_CATEGORY_LIST_H;
	
	onLBSelChanged 		= "_this spawn TTC_SHOP_UI_fnc_onCategorySelected;";
};
