/*
    Created by BauerMitFackel
*/

// WIDTH and HEIGHT
#define TTC_SHOP_UI_SHOPPING_CART_HEADER_W						TTC_SHOP_UI_COLUMN_RIGHT_W
#define TTC_SHOP_UI_SHOPPING_CART_HEADER_H						TTC_SHOP_UI_COLUMN_HEADER_H
#define TTC_SHOP_UI_SHOPPING_CART_SAVE_W						__ROUND(TTC_SHOP_UI_COLUMN_RIGHT_W / 3)
#define TTC_SHOP_UI_SHOPPING_CART_SAVE_H						__ROUND(0.035 * TTC_SHOP_UI_SZ_H)
#define TTC_SHOP_UI_SHOPPING_CART_LOAD_W						TTC_SHOP_UI_SHOPPING_CART_SAVE_W
#define TTC_SHOP_UI_SHOPPING_CART_LOAD_H						TTC_SHOP_UI_SHOPPING_CART_SAVE_H
#define TTC_SHOP_UI_SHOPPING_CART_CLEAR_W						TTC_SHOP_UI_COLUMN_RIGHT_W - TTC_SHOP_UI_SHOPPING_CART_SAVE_W - TTC_SHOP_UI_SHOPPING_CART_LOAD_W
#define TTC_SHOP_UI_SHOPPING_CART_CLEAR_H						TTC_SHOP_UI_SHOPPING_CART_SAVE_H
#define TTC_SHOP_UI_SHOPPING_CART_COSTS_W						TTC_SHOP_UI_COLUMN_RIGHT_W
#define TTC_SHOP_UI_SHOPPING_CART_COSTS_H						__ROUND(0.05 * TTC_SHOP_UI_SZ_H)
#define TTC_SHOP_UI_CLOSE_W										__ROUND(TTC_SHOP_UI_COLUMN_RIGHT_W * 0.3)
#define TTC_SHOP_UI_CLOSE_H										__ROUND(0.05 * TTC_SHOP_UI_SZ_H)
#define TTC_SHOP_UI_BUY_W										__ROUND((TTC_SHOP_UI_COLUMN_RIGHT_W * 0.7) - TTC_SHOP_UI_SPACING)
#define TTC_SHOP_UI_BUY_H										TTC_SHOP_UI_CLOSE_H
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_W		TTC_SHOP_UI_COLUMN_RIGHT_W
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_H		TTC_SHOP_UI_COLUMN_RIGHT_H - (TTC_SHOP_UI_SHOPPING_CART_HEADER_H + TTC_SHOP_UI_SHOPPING_CART_SAVE_H + TTC_SHOP_UI_SHOPPING_CART_COSTS_H + TTC_SHOP_UI_CLOSE_H + TTC_SHOP_UI_SPACING)
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_W				TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_W
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_H				TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_H

// X and Y
#define TTC_SHOP_UI_SHOPPING_CART_HEADER_X						TTC_SHOP_UI_COLUMN_RIGHT_X
#define TTC_SHOP_UI_SHOPPING_CART_HEADER_Y						TTC_SHOP_UI_COLUMN_RIGHT_Y
#define TTC_SHOP_UI_SHOPPING_CART_SAVE_X						TTC_SHOP_UI_COLUMN_RIGHT_X
#define TTC_SHOP_UI_SHOPPING_CART_SAVE_Y						TTC_SHOP_UI_SHOPPING_CART_HEADER_Y + TTC_SHOP_UI_SHOPPING_CART_HEADER_H
#define TTC_SHOP_UI_SHOPPING_CART_LOAD_X						TTC_SHOP_UI_SHOPPING_CART_SAVE_X + TTC_SHOP_UI_SHOPPING_CART_SAVE_W
#define TTC_SHOP_UI_SHOPPING_CART_LOAD_Y						TTC_SHOP_UI_SHOPPING_CART_SAVE_Y
#define TTC_SHOP_UI_SHOPPING_CART_CLEAR_X						TTC_SHOP_UI_SHOPPING_CART_LOAD_X + TTC_SHOP_UI_SHOPPING_CART_LOAD_W
#define TTC_SHOP_UI_SHOPPING_CART_CLEAR_Y						TTC_SHOP_UI_SHOPPING_CART_SAVE_Y
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_X		TTC_SHOP_UI_COLUMN_RIGHT_X
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_Y		TTC_SHOP_UI_SHOPPING_CART_SAVE_Y + TTC_SHOP_UI_SHOPPING_CART_SAVE_H
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_X				TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_X
#define TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_Y				TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_Y
#define TTC_SHOP_UI_SHOPPING_CART_COSTS_X						TTC_SHOP_UI_COLUMN_RIGHT_X
#define TTC_SHOP_UI_SHOPPING_CART_COSTS_Y						TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_Y + TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_H
#define TTC_SHOP_UI_CLOSE_X										TTC_SHOP_UI_COLUMN_RIGHT_X
#define TTC_SHOP_UI_CLOSE_Y										TTC_SHOP_UI_SHOPPING_CART_COSTS_Y + TTC_SHOP_UI_SHOPPING_CART_COSTS_H + TTC_SHOP_UI_SPACING
#define TTC_SHOP_UI_BUY_X										TTC_SHOP_UI_CLOSE_X + TTC_SHOP_UI_CLOSE_W + TTC_SHOP_UI_SPACING
#define TTC_SHOP_UI_BUY_Y										TTC_SHOP_UI_CLOSE_Y


class TTC_SHOP_ShopDialog_ShoppingCart_Header : TTC_UI_Text {
			
	idc					= 53001;
	moving				= true;
	style				= TTC_UI_STYLE_CENTER;
	colorBackground[]	= TTC_UI_COLOR_BLACK_A25;
	text				= "SHOPPING CART";
	x 					= TTC_SHOP_UI_SHOPPING_CART_HEADER_X;
	y 					= TTC_SHOP_UI_SHOPPING_CART_HEADER_Y;
	w 					= TTC_SHOP_UI_SHOPPING_CART_HEADER_W;
	h 					= TTC_SHOP_UI_SHOPPING_CART_HEADER_H;
};

class TTC_SHOP_ShopDialog_ShoppingCart_Save: TTC_UI_Button {
		
	idc		= 53002;
	text	= "Save";
	x		= TTC_SHOP_UI_SHOPPING_CART_SAVE_X;
	y		= TTC_SHOP_UI_SHOPPING_CART_SAVE_Y;
	w		= TTC_SHOP_UI_SHOPPING_CART_SAVE_W;
	h		= TTC_SHOP_UI_SHOPPING_CART_SAVE_H;
	
	action 	= "[] spawn TTC_SHOP_UI_fnc_onSaveClicked;";
};

class TTC_SHOP_ShopDialog_ShoppingCart_Load: TTC_UI_Button {

	idc		= 53003;
	text	= "Load";
	x		= TTC_SHOP_UI_SHOPPING_CART_LOAD_X;
	y		= TTC_SHOP_UI_SHOPPING_CART_LOAD_Y;
	w		= TTC_SHOP_UI_SHOPPING_CART_LOAD_W;
	h		= TTC_SHOP_UI_SHOPPING_CART_LOAD_H;
	
	action	= "[] spawn TTC_SHOP_UI_fnc_onLoadClicked;";
};

class TTC_SHOP_ShopDialog_ShoppingCart_Clear: TTC_UI_Button {

	idc		= 53004;
	text	= "Clear";
	x 		= TTC_SHOP_UI_SHOPPING_CART_CLEAR_X;
	y 		= TTC_SHOP_UI_SHOPPING_CART_CLEAR_Y;
	w 		= TTC_SHOP_UI_SHOPPING_CART_CLEAR_W;
	h 		= TTC_SHOP_UI_SHOPPING_CART_CLEAR_H;
	
	action	= "[] spawn TTC_SHOP_UI_fnc_onClearClicked;";
};

class TTC_SHOP_ShopDialog_ShoppingCart_ArticleList_Background: TTC_UI_Background {
		
	idc	= 53005;
	x 	= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_X;
	y 	= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_Y;
	w 	= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_W;
	h 	= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_BACKGROUND_H;
};

class _TTC_SHOP_ShopDialog_ShoppingCart_ArticleList_Minus: TTC_UI_Button {

	idc		= 53006;
	text	= "-";
	colorBackground[] = TTC_UI_COLOR_WHITE_A100;
	colorText[] = TTC_UI_COLOR_BLACK_A100;
	
	action	= "[] spawn TTC_SHOP_UI_fnc_onMinusClicked;";
};

class _TTC_SHOP_ShopDialog_ShoppingCart_ArticleList_Plus: TTC_UI_Button {

	idc		= 53007;
	text	= "+";
	colorBackground[] = TTC_UI_COLOR_WHITE_A100;
	colorText[] = TTC_UI_COLOR_BLACK_A100;
	
	action	= "[] spawn TTC_SHOP_UI_fnc_onPlusClicked;";
};

class TTC_SHOP_ShopDialog_ShoppingCart_ArticleList: TTC_UI_ListNBox {
		
	idc				= 53008;
	sizeEx			= TTC_UI_TEXT_SIZE_S;
	rowHeight		= 0.07;
	columns[]		= {0.08, 0.15, 0.7};
	drawSideArrows	= 0;
	idcLeft 		= 53006;
	idcRight 		= 53007;
	x 				= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_X;
	y 				= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_Y;
	w 				= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_W;
	h 				= TTC_SHOP_UI_SHOPPING_CART_ARTICLE_LIST_H;
};

class TTC_SHOP_ShopDialog_ShoppingCart_Costs : TTC_UI_StructuredText {
		
	idc					= 53009;
	colorBackground[]	= TTC_UI_COLOR_BLACK_A100;
	text				= "";
	sizeEx 				= TTC_UI_TEXT_SIZE_XL;
	style 				= TTC_UI_STYLE_RIGHT;
	x 					= TTC_SHOP_UI_SHOPPING_CART_COSTS_X;
	y 					= TTC_SHOP_UI_SHOPPING_CART_COSTS_Y;
	w 					= TTC_SHOP_UI_SHOPPING_CART_COSTS_W;
	h 					= TTC_SHOP_UI_SHOPPING_CART_COSTS_H;
};

class TTC_SHOP_ShopDialog_Close: TTC_UI_ButtonDanger {
		
	idc		= 53010;
	text	= "Close";
	sizeEx	= TTC_UI_TEXT_SIZE_XL;
	x 		= TTC_SHOP_UI_CLOSE_X;
	y 		= TTC_SHOP_UI_CLOSE_Y;
	w 		= TTC_SHOP_UI_CLOSE_W;
	h 		= TTC_SHOP_UI_CLOSE_H;
	
	action	= "closeDialog 0;";
};

class TTC_SHOP_ShopDialog_Buy: TTC_UI_ButtonSuccess {

	idc		= 53011;
	text	= "Buy";
	sizeEx	= TTC_UI_TEXT_SIZE_XL;
	x 		= TTC_SHOP_UI_BUY_X;
	y 		= TTC_SHOP_UI_BUY_Y;
	w 		= TTC_SHOP_UI_BUY_W;
	h 		= TTC_SHOP_UI_BUY_H;
	
	action	= "[] spawn TTC_SHOP_UI_fnc_onBuyClicked;";
};
