/*
    Created by BauerMitFackel
*/

// WIDTH and HEIGHT
#define TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_W		__ROUND(TTC_SHOP_UI_COLUMN_MIDDLE_W * 0.4)
#define TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_H		__ROUND(0.15 * TTC_SHOP_UI_SZ_H)
#define TTC_SHOP_UI_ARTICLE_PICTURE_W					__ROUND(TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_W - (2 * TTC_SHOP_UI_SPACING))
#define TTC_SHOP_UI_ARTICLE_PICTURE_H					__ROUND(TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_H - (2 * TTC_SHOP_UI_SPACING))
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_W		__ROUND((TTC_SHOP_UI_COLUMN_MIDDLE_W * 0.6) - TTC_SHOP_UI_SPACING)
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_H		__ROUND(0.15 * TTC_SHOP_UI_SZ_H)
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_W				TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_W
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_H				TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_H
#define TTC_SHOP_UI_ARTICLE_LIST_HEADER_W				TTC_SHOP_UI_COLUMN_MIDDLE_W
#define TTC_SHOP_UI_ARTICLE_LIST_HEADER_H				TTC_SHOP_UI_COLUMN_HEADER_H
#define TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_W			TTC_SHOP_UI_COLUMN_MIDDLE_W
#define TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_H			TTC_SHOP_UI_COLUMN_MIDDLE_H - TTC_SHOP_UI_ARTICLE_LIST_HEADER_H - TTC_SHOP_UI_ARTICLE_DESCRIPTION_H - TTC_SHOP_UI_SPACING
#define TTC_SHOP_UI_ARTICLE_LIST_W						TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_W
#define TTC_SHOP_UI_ARTICLE_LIST_H						TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_H
// X and Y
#define TTC_SHOP_UI_ARTICLE_LIST_HEADER_X				TTC_SHOP_UI_COLUMN_MIDDLE_X
#define TTC_SHOP_UI_ARTICLE_LIST_HEADER_Y				TTC_SHOP_UI_COLUMN_MIDDLE_Y
#define TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_X			TTC_SHOP_UI_COLUMN_MIDDLE_X
#define TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_Y			TTC_SHOP_UI_ARTICLE_LIST_HEADER_Y + TTC_SHOP_UI_ARTICLE_LIST_HEADER_H
#define TTC_SHOP_UI_ARTICLE_LIST_X						TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_X
#define TTC_SHOP_UI_ARTICLE_LIST_Y						TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_Y
#define TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_X		TTC_SHOP_UI_COLUMN_MIDDLE_X
#define TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_Y		TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_Y + TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_H + TTC_SHOP_UI_SPACING
#define TTC_SHOP_UI_ARTICLE_PICTURE_X					TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_X + TTC_SHOP_UI_SPACING
#define TTC_SHOP_UI_ARTICLE_PICTURE_Y					TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_Y + TTC_SHOP_UI_SPACING
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_X		TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_X + TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_W + TTC_SHOP_UI_SPACING
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_Y		TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_Y
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_X				0
#define TTC_SHOP_UI_ARTICLE_DESCRIPTION_Y				0


class TTC_SHOP_ShopDialog_ArticleList_Header: TTC_UI_Text {
			
	idc					= 52001;
	moving				= true;
	style				= TTC_UI_STYLE_CENTER;
	colorBackground[]	= TTC_UI_COLOR_BLACK_A25;
	text				= "ARTICLES";
	x 					= TTC_SHOP_UI_ARTICLE_LIST_HEADER_X;
	y 					= TTC_SHOP_UI_ARTICLE_LIST_HEADER_Y;
	w 					= TTC_SHOP_UI_ARTICLE_LIST_HEADER_W;
	h 					= TTC_SHOP_UI_ARTICLE_LIST_HEADER_H;
};

class TTC_SHOP_ShopDialog_ArticleList_Background: TTC_UI_Background {
	
	idc					= 52002;
	x					= TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_X;
	y					= TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_Y;
	w					= TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_W;
	h					= TTC_SHOP_UI_ARTICLE_LIST_BACKGROUND_H;
};

class TTC_SHOP_ShopDialog_ArticleList: TTC_UI_ListNBox {

	idc					= 52003;
	rowHeight			= 0.07;
	columns[]			= {-0.001, 0.80};
	x 					= TTC_SHOP_UI_ARTICLE_LIST_X;
	y 					= TTC_SHOP_UI_ARTICLE_LIST_Y;
	w 					= TTC_SHOP_UI_ARTICLE_LIST_W;
	h 					= TTC_SHOP_UI_ARTICLE_LIST_H;
	
	onLBSelChanged 		= "_this spawn TTC_SHOP_UI_fnc_onArticleSelected;";
	onLBDblClick		= "_this spawn TTC_SHOP_UI_fnc_onArticleDoubleClicked;";
};

class TTC_SHOP_ShopDialog_ArticlePicture_Background: TTC_UI_Background {
			
	idc 				= 52004;
	colorBackground[]	= TTC_UI_COLOR_WHITE_A75;
	x					= TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_X;
	y					= TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_Y;
	w					= TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_W;
	h					= TTC_SHOP_UI_ARTICLE_PICTURE_BACKGROUND_H;
};

class TTC_SHOP_ShopDialog_ArticlePicture: TTC_UI_Picture {

	idc					= 52005;
	x					= TTC_SHOP_UI_ARTICLE_PICTURE_X;
	y					= TTC_SHOP_UI_ARTICLE_PICTURE_Y;
	w					= TTC_SHOP_UI_ARTICLE_PICTURE_W;
	h					= TTC_SHOP_UI_ARTICLE_PICTURE_H;
};

class TTC_SHOP_ShopDialog_ArticleDescription_Container: TTC_UI_ControlsGroup {
		
	idc					= 52100;
	x					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_X;
	y					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_Y;
	w					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_W;
	h					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_CONTAINER_H;
	
	class Controls {
		
		class TTC_SHOP_ShopDialog_ArticleDescription: TTC_UI_StructuredText {
		
			idc					= 52101;
			style				= TTC_UI_STYLE_CENTER + TTC_UI_STYLE_MULTI;
			colorBackground[]	= TTC_UI_COLOR_BLACK_A75;
			x					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_X;
			y					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_Y;
			w					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_W;
			h					= TTC_SHOP_UI_ARTICLE_DESCRIPTION_H;
		};
	};
};
