/*
	Style definitions
    Created by BauerMitFackel
*/

#define TTC_UI_STYLE_POS						0x0F
#define TTC_UI_STYLE_HPOS						0x03
#define TTC_UI_STYLE_VPOS						0x0C
#define TTC_UI_STYLE_LEFT						0x00
#define TTC_UI_STYLE_RIGHT						0x01
#define TTC_UI_STYLE_CENTER						0x02
#define TTC_UI_STYLE_DOWN						0x04
#define TTC_UI_STYLE_UP							0x08
#define TTC_UI_STYLE_VCENTER					0x0C
#define TTC_UI_STYLE_TYPE						0xF0
#define TTC_UI_STYLE_SINGLE						0x00
#define TTC_UI_STYLE_MULTI						0x10
#define TTC_UI_STYLE_TITLE_BAR					0x20
#define TTC_UI_STYLE_PICTURE					0x30
#define TTC_UI_STYLE_FRAME						0x40
#define TTC_UI_STYLE_BACKGROUND					0x50
#define TTC_UI_STYLE_GROUP_BOX					0x60
#define TTC_UI_STYLE_GROUP_BOX2					0x70
#define TTC_UI_STYLE_HUD_BACKGROUND				0x80
#define TTC_UI_STYLE_TILE_PICTURE				0x90
#define TTC_UI_STYLE_WITH_RECT					0xA0
#define TTC_UI_STYLE_LINE						0xB0
#define TTC_UI_STYLE_SHADOW						0x100
#define TTC_UI_STYLE_NO_RECT					0x200
#define TTC_UI_STYLE_KEEP_ASPECT_RATIO			0x800
#define TTC_UI_STYLE_TITLE						TTC_UI_STYLE_TITLE_BAR + TTC_UI_STYLE_CENTER

// Slider
#define TTC_UI_STYLE_SLIDER_DIR					0x400
#define TTC_UI_STYLE_SLIDER_VERT				0
#define TTC_UI_STYLE_SLIDER_HORZ				0x400
#define TTC_UI_STYLE_SLIDER_TEXTURES			0x10

// Progress Bar
#define TTC_UI_STYLE_PROGRESS_BAR_VERTICAL		0x01
#define TTC_UI_STYLE_PROGRESS_BAR_HORIZONTAL	0

// Listbox
#define TTC_UI_STYLE_LISTBOX_TEXTURES			0x10
#define TTC_UI_STYLE_LISTBOX_MULTI				0x20

// Tree
#define TTC_UI_STYLE_TREE_SHOWROOT				1
#define TTC_UI_STYLE_TREE_AUTOCOLLAPSE			2

// Message Box
#define TTC_UI_STYLE_MESSAGE_BOX_BUTTON_OK		1
#define TTC_UI_STYLE_MESSAGE_BOX_BUTTON_CANCEL	2
#define TTC_UI_STYLE_MESSAGE_BOX_BUTTON_USER	4
